### ISSUE TITLE
ParryPacket crash

### ISSUE THREAD

**Issue by S-Leader** [TeamMFR/MineFantasy-reborn#10]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2021-12-23 20:12:54 CST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at minefantasy.mfr.network.ParryPacket.execute(ParryPacket.java:39)
    at minefantasy.mfr.network.PacketMF.execute(PacketMF.java:50)
    at minefantasy.mfr.network.PacketHandlerMF.lambda$onClientPacket$1(PacketHandlerMF.java:30)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_261, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4072143280 bytes (3883 MB) / 6600785920 bytes (6295 MB) up to 7409238016 bytes (7066 MB)
  JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx7065m
  IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 32 mods loaded, 32 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                             | Version           | Source                                                          | Signature                                |
       |:------ |:------------------------------ |:----------------- |:--------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                      | 1.12.2            | minecraft.jar                                                   | None                                     |
       | LCHIJA | mcp                            | 9.42              | minecraft.jar                                                   | None                                     |
       | LCHIJA | FML                            | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                          | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | foamfixcore                    | 7.7.4             | minecraft.jar                                                   | None                                     |
       | LCHIJA | codechickenlib                 | 3.2.3.358         | [CodeChicken Lib] CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | waila                          | 1.8.26            | [Here's What You're Looking At] Hwyla-1.8.26-B41_1.12.2.jar     | None                                     |
       | LCHIJA | jei                            | 4.16.1.302        | [JEI物品管理器] jei_1.12.2-4.16.1.302.jar                            | None                                     |
       | LCHIJA | vanillafix                     | 1.0.10-150        | [原版修复] VanillaFix-1.0.10-150.jar                                | None                                     |
       | LCHIJA | baubles                        | 1.5.2             | [饰品栏] Baubles-1.12-1.5.2.jar                                    | None                                     |
       | LCHIJA | thaumcraft                     | 6.1.BETA26        | [神秘时代] Thaumcraft-1.12.2-6.1.BETA26.jar                         | None                                     |
       | LCHIJA | lostmagic                      | 1.0               | [失落魔法]lostmagic-1.0.2.jar                                       | None                                     |
       | LCHIJA | ebwizardry                     | 4.3.4             | [巫术学] ElectroblobsWizardry-4.3.4-MC1.12.2.jar                   | None                                     |
       | LCHIJA | twilightforest                 | 3.11.1021         | [暮色森林] twilightforest-1.12.2-3.11.1021-universal.jar            | None                                     |
       | LCHIJA | tfspellpack                    | 1.1.0             | [巫术学：暮色森林法术包] TFSpellPack-1.1.0-MC1.12.2.jar                    | None                                     |
       | LCHIJA | journeymap                     | 1.12.2-5.7.1      | [旅行地图] journeymap-1.12.2-5.7.1.jar                              | None                                     |
       | LCHIJA | botania                        | r1.10-364         | [植物魔法] Botania r1.10-364.4.jar                                  | None                                     |
       | LCHIJA | abyssalcraft                   | 2.0.0-ALPHA-4     | [深渊国度] AbyssalCraft-1.12.2-2.0.0-ALPHA-4.jar                    | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | thaumicperiphery               | 0.3.1             | [神秘外饰]thaumicperiphery-0.3.1.jar                                | None                                     |
       | LCHIJA | thaumicwonders                 | 1.8.2             | [神秘奇境]thaumicwonders-1.8.2.jar                                  | None                                     |
       | LCHIJA | lanserverproperties            | 1.0               | [自定义局域网联机] lanserverproperties-1.0.jar                          | None                                     |
       | LCHIJA | mousetweaks                    | 2.10.1            | [鼠标手势] MouseTweaks-2.10.1-mc1.12.2.jar                          | None                                     |
       | LCHIJA | foamfix                        | 0.10.14-1.12.2    | foamfix-0.10.14-1.12.2.jar                                      | None                                     |
       | LCHIJA | minefantasyreforged            | 1.12.2-0.1.2-BETA | minefantasyreforged-1.12.2-0.1.2-BETA.jar                       | None                                     |
       | LCHIJA | tcresearchpatcher              | 1.12.2-1.1.3      | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar                      | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicaugmentation            | 1.12.2-2.1.5      | ThaumicAugmentation-1.12.2-2.1.5.jar                            | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicjei                     | 1.6.0             | ThaumicJEI-1.12.2-1.6.0-27.jar                                  | None                                     |
       | LCHIJA | tombmanygraves                 | 1.12-4.2.0        | TombManyGraves-1.12-4.2.0.jar                                   | None                                     |
       | LCHIJA | tombmanygraves2api             | 1.12.2-1.0.0      | tombmanygraves2api-1.12.2-1.0.0.jar                             | None                                     |
       | LCHIJA | thebetweenlands                | 3.8.1             | TheBetweenlands-3.8.1-universal.jar                             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | tombmanypluginsthebetweenlands | 1.0.0             | tombmanypluginsthebetweenlands-1.0.0.jar                        | None                                     |
       | LCHIJA | jade                           | 0.1.0             | [玉 🔍] Jade-0.1.0.jar                                           | None                                     |
  Loaded coremods (and transformers): Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.1-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      VanillaFixLoadingPlugin ([原版修复] VanillaFix-1.0.10-150.jar)
                                        
                                      MinefantasyReforged (minefantasyreforged-1.12.2-0.1.2-BETA.jar)
                                        
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.5.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics'
  Suspected Mods: Minefantasy Reforged (minefantasyreforged)

**Comment by ThatPolishKid99** [comment]
Can we get more information for this? We can tell that you were parrying, but where were you parrying, with what weapon, and any other information that might be useful

**Comment by ThatPolishKid99** [comment]
Can we get more information for this? We can tell that you were parrying, but where were you parrying, with what weapon, and any other information that might be useful

**Comment by ThatPolishKid99** [comment]
Also is this a singleplayer or multiplayer crash?

**Comment by S-Leader** [comment]
> Also is this a singleplayer or multiplayer crash?

multiplayer

**Comment by linxcy** [comment]
i'm one of the player.
i just use the shield magic in mod Electroblob's Wizardry to parry the dragon breath or maybe dragon's physical attack but the game crash.
the dragon is a normal red dragon.
the game is a lan-sever.

**Comment by Pelirow** [comment]
> i'm one of the player. i just use the shield magic in mod Electroblob's Wizardry to parry the dragon breath or maybe dragon's physical attack but the game crash. the dragon is a normal red dragon. the game is a lan-sever.

Can you please provide additional details? What EB Wiz spell exactly was being used, what wand, what gear or baubles, the specific dragon you were fighting, and what you mean by "parry the dragon breath" and caused the crash? Nothing but MFR weapons should be able to parry. We are unable to replicate this crash with the provided info so far, so as much detail as you can provide would be greatly appreciated.

**Comment by linxcy** [comment]
i use this spell
it works like vanilla shield.
![image](https://user-images.githubusercontent.com/67699852/147723099-1d082887-0629-402a-931b-f846ae61e10c.png)
And this is the baubles i wear.
![image](https://user-images.githubusercontent.com/67699852/147723264-fc4332f6-9f92-4368-9516-42125e9f714d.png)
the wand is this one.
![image](https://user-images.githubusercontent.com/67699852/147723988-d1689915-fa25-4332-94ea-69c44144dbd9.png)

**Comment by Pelirow** [comment]
>And this is the baubles i wear. ![image](https://user-images.githubusercontent.com/67699852/147723264-fc4332f6-9f92-4368-9516-42125e9f714d.png) 

Thanks a bunch, one last request: can you provide the names of the baubles and the mods they come from?

**Comment by linxcy** [comment]
![image](https://user-images.githubusercontent.com/67699852/147800264-0dc2f611-5dbc-43f0-bc50-039f62ba1558.png)
![image](https://user-images.githubusercontent.com/67699852/147800278-bbaec544-e6f7-40fd-9430-631cf441f56d.png)
![image](https://user-images.githubusercontent.com/67699852/147800283-4acf9bc8-74aa-4c7d-9a42-1286694638f8.png)
![image](https://user-images.githubusercontent.com/67699852/147800285-e81c88f8-c327-4b6b-a1df-6505cb66a478.png)

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0 (at least in theory)
