### ISSUE TITLE
Tanning Racks permanently unusable after breaking

### ISSUE THREAD

**Issue by Pelirow** [TeamMFR/MineFantasy-reborn#13]
Rack broken by hand with hide on it. Dropped: hide, rack, and leather I had not yet actually produced.
![image](https://user-images.githubusercontent.com/8356065/147684755-869dea8c-4b65-4833-a5ac-ddfc771c4106.png)

After a rack gets borked: the output information on the GUI bar is no longer there, and knife will do parry-ready stance.
![image](https://user-images.githubusercontent.com/8356065/147685139-ccd27d71-d7c0-45a3-8b72-5abd74e9ff09.png)

When a shabby tanning rack is broken by hand while it has a small, medium, or large hide on it, sometime it will bork out and drop with the hide, the rack, AND some leather. If the rack is broken while it has leather on it, it will sometime drop the leather, the rack, AND leather strips.

After the shabby rack bugs out with the funky drops after being broken, ANY tanning rack becomes unusable for the type of hide that was on the rack, and leather is also unable to be sheared. The "#x Leather" output indicator does not show up on the GUI bar when looking at the rack while holding a knife, and instead of swinging at the hide when right clicking, the knife does the parry-ready stance instead.

**Comment by Pelirow** [comment]
[2021-12-29-1.log.gz](https://github.com/TeamMFR/MineFantasyReforged/files/7789947/2021-12-29-1.log.gz)

TPK requested log.

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
