### ISSUE TITLE
Tough as nails VS Minefantasy GUI issue

### ISSUE THREAD

**Issue by SaltyyCoffee** [TeamMFR/MineFantasy-reborn#14]
The temperature GUI from tough as nails is located in a location where it blocks the center of the anvil's GUI, making it hard to determine where you are when smithing.
![2022-01-04_20 49 25](https://user-images.githubusercontent.com/56376173/148147976-4f558b3f-6a1b-4a21-b486-bcc1e5e303c8.png)

**Comment by ThatPolishKid99** [comment]
Tough as Nails handles that little circle in the middle in a really annoyingly general way, but I will deal with it because MFR is in 1.12

**Comment by ainlzj** [comment]
It's serious for obsessive-compulsive disorder
