### ISSUE TITLE
Engineering Tools allows recipes without the rest of the ingredients

### ISSUE THREAD

**Issue by S-Leader** [TeamMFR/MineFantasy-reborn#15]
![2022-01-07_19 08 35](https://user-images.githubusercontent.com/92129388/148535483-7fa7d6f0-f1c0-4d91-8cda-4910ad5b1da8.png)

**Comment by ThatPolishKid99** [comment]
I need an explanation for what is happening in this screenshot

**Comment by S-Leader** [comment]
![image](https://user-images.githubusercontent.com/92129388/148641938-ce89232a-84d7-47e0-b64f-6b59901fb2de.png)
Only one engineered tools can craft empty syringe.

English is not my mother language, sorry for inconvenience,
