### ISSUE TITLE
JEI doesn’t display bottom right part of large MFR recipes

### ISSUE THREAD

**Issue by S-Leader** [TeamMFR/MineFantasy-reborn#16]
![2022-01-07_19 10 50](https://user-images.githubusercontent.com/92129388/148535692-3e8d5c08-0d25-4c00-affc-2ddd992baea3.png)

**Comment by ThatPolishKid99** [comment]
We are are aware of this, it’s just a small bug with the JEI compat. The recipe is still accurate, just not displaying correctly in JEI.

**Comment by ThatPolishKid99** [comment]
Fixed in latest update
