### ISSUE TITLE
Dragon can't be summoned on server (mohist & sponge)

### ISSUE THREAD

**Issue by P303030P** [TeamMFR/MineFantasy-reborn#17]
In singleplayer mode, dragon could be summoned. During my play on mohist server, there is no dragon appearing.
I ve also test it on the sponge server with only MFF installed. It showed "Skipping Entity with id minefantasyreforged:dragon"

![image](https://user-images.githubusercontent.com/97388220/148680679-e5901ac7-4351-4397-b04f-aea445d19618.png)
on mohist
![image](https://user-images.githubusercontent.com/97388220/148680793-3da880b1-b38d-4726-9f65-8de03cf4abf3.png)
on sponge

**Comment by ThatPolishKid99** [comment]
Make sure you are on the latest version of MFR and try that again on Sponge. I will not guarantee things work on CatServer and I will not spend overly long tracking down issues on that server platform

**Comment by P303030P** [comment]
> Make sure you are on the latest version of MFR and try that again on Sponge. I will not guarantee things work on CatServer and I will not spend overly long tracking down issues on that server platform

tried it again on the sponge server, replace MFF 0.1.2 with MFF 0.1.3
(spongeforge-1.12.2-2838-7.4.7, forge-1.12.2-14.23.5.2860)

dragon successfully summoned
![image](https://user-images.githubusercontent.com/97388220/148691290-da3bfd0a-fe23-4ff0-9708-f6392bb3d026.png)

THX
looking forward to your future update!
