### ISSUE TITLE
When MF2 0.1.3 coexists with vanilla immersion, the composite will disappear

### ISSUE THREAD

**Issue by ainlzj** [TeamMFR/MineFantasy-reborn#20]
When MF2 0.1.3 and vanilla-immersion coexist, the crafting item will disappear, it can be crafted on the inventory, but not on the workbench, delete vanilla-immersion can

**Comment by ThatPolishKid99** [comment]
I have no idea what this is trying to tell me? Please explain what you mean.

**Comment by ainlzj** [comment]
I'm sorry, my statement is inappropriate, if you combine it, the item will disappear.

**Comment by ThatPolishKid99** [comment]
I still have no context? What is vanilla immersion, what crafting item disappears, in which inventory?

**Comment by ainlzj** [comment]
![QQ录屏20220124031522 00_00_00-00_00_30](https://user-images.githubusercontent.com/66135518/150694456-c36fe08b-1326-4d76-9d49-f53ade93fa19.gif)

**Comment by ThatPolishKid99** [comment]
I don’t see how this is an MFR issue. This might be related to timber recipe bug. Maybe you can test this again when the fix for that release

**Comment by ainlzj** [comment]
When I return to 0.1.2, there is no bug

**Comment by ainlzj** [comment]
It's good to have him crafted in the inventory

**Comment by ThatPolishKid99** [comment]
The timber bug was introduced in 1.3, so if it’s not present in 1.2, then we can assume it’s that. I’ll leave this open for now, but I’ll probably close it when I release the fix

**Comment by ainlzj** [comment]
almost all synthetic

**Comment by ainlzj** [comment]
1.2 doesn't have this problem, now I'm playing 1.2

**Comment by ThatPolishKid99** [comment]
This should be fixed in the latest updates. Feel free to reopen if that is not the case
