### ISSUE TITLE
Holding a Primitive Pickaxe after crafting causes a NullPointerException

### ISSUE THREAD

**Issue by Landmaster13** [TeamMFR/MineFantasy-reborn#23]
Issue arose when picking up a Primitive Pickaxe out of a crafting bench, and walking away. I will be attaching the aforementioned crash report
[crash-2022-02-08_20.29.59-client.txt](https://github.com/TeamMFR/MineFantasyReforged/files/8026578/crash-2022-02-08_20.29.59-client.txt)
.

**Comment by ThatPolishKid99** [comment]
This bug occurs when right clicking air with any MFR pickaxe. It is fixed in dev and will be part of the next update.
