### ISSUE TITLE
Equipping a Zombie Head into your helmet slot gives a stamina regeneration penalty

### ISSUE THREAD

**Issue by Landmaster13** [TeamMFR/MineFantasy-reborn#24]
If you equip a Zombie Head on your character, when moving you'll hear the heavy armor movement sound playing, in addition to stamina taking a noticeably longer time to regenerate back to maximum.

**Comment by ThatPolishKid99** [comment]
I am not able to replicate this in the latest MFR version. Please provide more information

**Comment by Landmaster13** [comment]
I can provide a video of this, I will post it when prepared.

**Comment by ThatPolishKid99** [comment]
That works too, but I meant for like, the MFR version you’re using

**Comment by Landmaster13** [comment]
This was tested on the latest version (0.1.5 BETA) on a server
