### ISSUE TITLE
Scrolling beyond the bounds of the Research Book causes the screen's brightness to darken

### ISSUE THREAD

**Issue by Landmaster13** [TeamMFR/MineFantasy-reborn#25]
![image](https://user-images.githubusercontent.com/35228138/153090291-695ad3c6-4ac1-4543-8534-b979323af76a.png)
![image](https://user-images.githubusercontent.com/35228138/153090302-1ebced44-8bb0-437d-bda3-8268075858df.png)

**Comment by Landmaster13** [comment]
Graphics also clip out of bounds as well.
![image](https://user-images.githubusercontent.com/35228138/153091261-43cb4bd8-47e2-4ece-a170-21b927286712.png)

**Comment by ThatPolishKid99** [comment]
This is a relatively minor thing. Might fix it when I introduce data driven registries for the research book in the far future
