### ISSUE TITLE
Disabling skill book recipes in the config doesn't disable them in game

### ISSUE THREAD

**Issue by TheHaterofGravel** [TeamMFR/MineFantasy-reborn#27]
The config setting in "Hardcore.cfg"-

# Skill books recipes will be disabled, but you still can find them it the world.
    B:"Remove Books Recipes"=true

Will not disable the recipe for skill books, I assume it might apply to the talisman recipes too, but I have not tested those specifically.

**Comment by ThatPolishKid99** [comment]
There is no config option for completely removing skillbooks from the game, just their recipes. I will close this one in favor of #31. If you want to suggest a config option for completely removing skillbooks, please join our discord and make one there.
