### ISSUE TITLE
Several crafing table recipes that should be shapeless are not shapeless

### ISSUE THREAD

**Issue by TheHaterofGravel** [TeamMFR/MineFantasy-reborn#29]
Some recipes that were shapeless in the 1.7.10 version are no longer shapeless, they should be able to be done in the 2x2 grid but spacers in the recipe prevent some from doing so. Examples include- cheese curds, sugar pots, clean hides, pies/cakes. 

version-
0.1.5-BETA

**Comment by ThatPolishKid99** [comment]
I would need a more complete list. Some of the thing you listed are valid, like clean hides. However, sugar pots are a 3x3 size recipe, cheese curds don't exist...

**Comment by ThatPolishKid99** [comment]
I would still appreciate a list if you can provide one, but I have gone through all of the crafting table recipes and changed the majority of recipes that should be "shapeless"
