### ISSUE TITLE
Mutiple config options do not function

### ISSUE THREAD

**Issue by TheHaterofGravel** [TeamMFR/MineFantasy-reborn#31]
I've already mentioned this in the skill book report, but it also seems a few other config options for the mod do not actually work.
These are some the ones that I've noticed not working-

Hardcore cfg: skillbooks, talismans, prevent furnace food, food burn at high temperature, do not seem to work

Crafting cfg: allow iron ingots to make pig iron, does not work

version-
0.1.5-BETA

**Comment by TheHaterofGravel** [comment]
@ThatPolishKid99 
You seem to have misunderstood my original post about skill books not getting their recipe disabled through the config option. I never stated that the issue was that they still generated I only mentioned that the config option related to them did not work at all. 

I also tested the talisman recipes and those seem to share the same issue as well, here is a couple images detailing what the issue is, shown with its related config option under the image.

![testnook1](https://user-images.githubusercontent.com/42475929/155617262-b528cd7a-7760-43e1-be41-3ecb91c2e087.png)

![talisman](https://user-images.githubusercontent.com/42475929/155617235-70685abd-4d5e-4531-b610-413f8f283b47.png)

Even with the recipes disabled in the config they still do not get their recipe disabled in game.

**Comment by ThatPolishKid99** [comment]
I understood your message, I just wanted to reduce duplicates, so I closed that issue in favor of this one explaining how most of those configs are broken. They are broken due to the migration to JSON based recipes.

**Comment by TheHaterofGravel** [comment]
Alright, just wanted to be sure you knew of the issue, since I don't know of any way to disable original recipes via the custom recipes config other than setting outputs to air, which still leaves the old recipes up in jei. 
Thank you for clarifying.

**Comment by ThatPolishKid99** [comment]
Fixed in the latest update
