### ISSUE TITLE
problems with jei

### ISSUE THREAD

**Issue by Biviho** [TeamMFR/MineFantasy-reborn#34]
hi, i was testing the mod in my modpack and then in a lighter modpack environment i made for testing and i'm having a lot of problems:

the modpack is quite big (330 mods) but i have never had a problem like this: basically looks like jei phases during startup take ages while your mod is installed, also causing a huge bloat in the pack memory usage (from normally around 5-6 gb to more than 8).
removing jei solves the issue...but yeah...removing jei is a issue.

in a light modpack environment (your mod the lib and jei) i'm instead having this crash
[crash-2022-03-02_02.06.43-client.txt](https://github.com/TeamMFR/MineFantasyReforged/files/8165879/crash-2022-03-02_02.06.43-client.txt)
wich looks like it's totally unrelated...but your is the only mod together with jei...

is your mod just incompatible with jei in a large modpack environment or it might be cause of the current beta status?

**Comment by ThatPolishKid99** [comment]
You should try adding the mixin compat mod. This crash report does not directly reference either JEI or MFR
