### ISSUE TITLE
Oddities with Superior Items

### ISSUE THREAD

**Issue by TheGazer** [TeamMFR/MineFantasy-reborn#35]
Today I ended up making a lot of superior equipment for the sake of testing. In this testing I found 2 things that I feel should be addressed.

1: Some Items do not receive a stat boost so far as I can tell. Armor and Crafting tools receive their bonuses properly, but Weapons and Tools don't. I cannot find a functional difference in two red steel shortswords even though one is meant to be superior, and I can't see a differences in the pickaxes either, though I could be wrong on those.

2: Tier 8 Metals do not become unbreakable. While Testing out Abyssalcraft's Ethaxium I noticed that even though It was meant to be superior it wasn't unbreakable. Presumably this is also true of higher tier metals as well, but I don't have any to test. While it is possible, I doubt that this issue is specific to Ethaxium

**Comment by ThatPolishKid99** [comment]
1.) Superior gives extra durability. 
2.) I plan to eventually replace the Superior makes the item Unbreakable thing with a more complex system of rewards for item quality, so i am not overly concerned about that. I deeply dislike the mechanic myself, I find it very lazy and plan to replace it wholesale.
