### ISSUE TITLE
Can't make Clay Bomb Casing

### ISSUE THREAD

**Issue by CKenJa** [TeamMFR/MineFantasy-reborn#36]
version 1.12.2-0.15-BETA

Even if the research is complete, you can still find it at ???? will appear as
![2022-03-08_23 13 37](https://user-images.githubusercontent.com/41111170/157255213-9249847d-2949-4921-9313-bba56dae591e.png)

**Comment by pianoyard** [comment]
Had a the same problem although once I had done the ceramic mine casing research I could craft the clay bomb casing
