### ISSUE TITLE
Bug in displaying unknown recipes on carpenter bench

### ISSUE THREAD

**Issue by CKenJa** [TeamMFR/MineFantasy-reborn#37]
Even after removing the unknown recipe, you can continue to visit ???? until you see the recipe you know. continues to appear.

![2022-03-08_23 22 32](https://user-images.githubusercontent.com/41111170/157256728-fab3db2f-3b2a-44f0-94a2-c742b2069ac3.png)

# process
1. Place unknown recipes
2. Remove items(???? as it is)
3. Place known recipes(get fixed)

**Comment by ThatPolishKid99** [comment]
This is a minor updating desync, it hardly matters in the long run
