### ISSUE TITLE
Advanced Tanning rack Item model facing is wrong.

### ISSUE THREAD

**Issue by CKenJa** [TeamMFR/MineFantasy-reborn#39]
Advanced Tanning Rack is facing different direction from other tanning racks and items.
![2022-03-08_23 55 29](https://user-images.githubusercontent.com/41111170/157263374-5cfb4944-07e3-4efa-897a-caf3b8629d45.png)

**Comment by ThatPolishKid99** [comment]
This is an utterly inconsequential thing. I will not even bother to fix this
