### ISSUE TITLE
Sneak and right click with bandage on other player cause game crash, but sever not crash

### ISSUE THREAD

**Issue by 1170991249** [TeamMFR/MineFantasy-reborn#4]

**Comment by toErIpNid** [comment]
Is there a crash log?

**Comment by 1170991249** [comment]
> Is there a crash log?

https://docs.google.com/document/d/1TjEEOVn6F3sSF3uH5zbKNscC9ezrAhwiNabB_854zHA/edit?usp=sharing

**Comment by ThatPolishKid99** [comment]
That crash report is inaccessible, please just upload the file directly to Github,

**Comment by 1170991249** [comment]
> That crash report is inaccessible, please just upload the file directly to Github,
[crash-2021-12-22_01.49.42-client.txt](https://github.com/TeamMFR/MineFantasyReforged/files/7761480/crash-2021-12-22_01.49.42-client.txt)

**Comment by 1170991249** [comment]
> That crash report is inaccessible, please just upload the file directly to Github,
[crash-2021-12-22_01.49.42-client.txt](https://github.com/TeamMFR/MineFantasyReforged/files/7761527/crash-2021-12-22_01.49.42-client.txt)

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
