### ISSUE TITLE
Incompatibility With Thaumic Arcana mod

### ISSUE THREAD

**Issue by UberbeastX** [TeamMFR/MineFantasy-reborn#41]
When using this mod and thaumic arcana when I use the heavy attack where you jump hold down shift and attack the game completely freezes.

**Comment by ThatPolishKid99** [comment]
This is no where near enough information. 
What version of the mod(s) are you running, what version of Forge, crash reports if they exist, log files if they don't, etc
Also, it would be useful to see some proof, like a video.

**Comment by UberbeastX** [comment]
Thaumic Arcana 1.3.1
Minefantasy Reforged 0.1.5

1.12.2 Forge 14.23.5.2860

No crash report 
Not really sure what other log to send 
I can try to make a video

**Comment by UberbeastX** [comment]
This is the latest log if that helps
[latest.log](https://github.com/TeamMFR/MineFantasyReforged/files/8457049/latest.log)
