### ISSUE TITLE
Unable to Craft Bows with Metal Joints

### ISSUE THREAD

**Issue by CCCClear** [TeamMFR/MineFantasy-reborn#43]
Players cannot craft bows with metal joints. 
At least there aren't any recipes in the book.
This seems to be a bug from MC1.7.10.

**Comment by ThatPolishKid99** [comment]
Not really a bug, just an unfinished feature. Luckily I have finished this feature for the next update. Join our discord to check out the preview images

**Comment by CCCClear** [comment]
Good to hear that and looking forward to it.
