### ISSUE TITLE
Cheese-style items duplication

### ISSUE THREAD

**Issue by Moroka** [TeamMFR/MineFantasy-reborn#45]
Hello! I am using minefantasyreforged-1.12.2-0.1.5-BETA.jar on public server with sponge

Pies, cheese and other sliced elements have a bug: in case of loss of support, they drop out completely (all interactions with them are lost), which allows you to make a column of the pie to collect 8 pieces from each and break the block under the column to get full pies back (saving at this pieces cut off from the pie)

**Comment by ThatPolishKid99** [comment]
Thanks for the report! Fixed in dev, and will be part of the next update
