### ISSUE TITLE
Incompatible with Locks Mod

### ISSUE THREAD

**Issue by CCCClear** [TeamMFR/MineFantasy-reborn#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

A single module test was carried out, and when using only either, the game started normally, but when both appeared, the game crashed and couldn't start.

### Expected behaviour

This incompatibility was not found in previous releases.

### Steps to reproduce

It crashes on startup. Therefore, no crash report is generated. 
Here is the debug file.

### Crashlog

https://gist.github.com/CCCClear/c28589241ef0b300cb0ba563fbaa6970

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

0.2.0

### Forge version

 1.12.2 - 14.23.5.2860

### Other mods

The Locks mod mentioned above is this one: 
https://www.curseforge.com/minecraft/mc-mods/locks
If this mod is causing the problem, I will post the issue to that mod as well.

**Comment by ThatPolishKid99** [comment]
You will likely need the Mixin Compat mod. Please try with that, and report back

**Comment by CCCClear** [comment]
Although I also thought this was a solution, it didn't work and still crashed on startup. 
Here is the debug log.
https://gist.github.com/CCCClear/1f4421848427fd3005ab91dc6083e403

**Comment by ThatPolishKid99** [comment]
Should be fixed with the latest update and the MixinBooter support
