### ISSUE TITLE
Compatible with liteloader？

### ISSUE THREAD

**Issue by 1866522477** [TeamMFR/MineFantasy-reborn#48]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Observed behaviour

[minecraft-exported-logs-2022-07-12T21-30-15.log](https://github.com/TeamMFR/MineFantasyReforged/files/9093374/minecraft-exported-logs-2022-07-12T21-30-15.log)

### Expected behaviour

![20220712213808](https://user-images.githubusercontent.com/40629602/178503464-513a3e22-1cdc-420a-9147-0a4ac2ee5245.jpg)

### Steps to reproduce

Unable to start the game

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

MineFantasyReforged-1.12.2-0.2.0

### Forge version

14.23.5.2860

**Comment by ThatPolishKid99** [comment]
Try using Mixin compat mod, I’m not sure why you have it disabled there

**Comment by 1866522477** [comment]
KO
![20220712215923](https://user-images.githubusercontent.com/40629602/178508522-a8327bf1-25ee-4658-b56e-63c1de17835a.jpg)
[minecraft-exported-logs-2022-07-12T21-57-44.log](https://github.com/TeamMFR/MineFantasyReforged/files/9093668/minecraft-exported-logs-2022-07-12T21-57-44.log)

**Comment by 1866522477** [comment]
...Because I tried

**Comment by 1866522477** [comment]
....Because I tried

**Comment by ThatPolishKid99** [comment]
I will try to figure this out, but Mixin compat should fix this issue.

**Comment by ThatPolishKid99** [comment]
Should be fixed with the latest update and the MixinBooter support
