### ISSUE TITLE
[Bug] disabling armor slowdown leaves sinking in water active

### ISSUE THREAD

**Issue by assasinwar9** [TeamMFR/MineFantasy-reborn#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

even with all the armor options in all configs turned off etc, it still makes you sink like a rock in water, and prevents swimming up...

### Expected behaviour

disabling armor slowdown should disable all the things directly tied to that system, as far as i can tell sinking if your armor weighs a certain amount etc should be disabled as well

### Steps to reproduce

start playing with this mod, wear armor that is mediem or heavy etc , jump in water... drown , disable armor slowdown in config, walk into water, have to close mc becuse sinking is still a thing

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

MineFantasyReforged-1.12.2-0.2.0

### Forge version

1.12.2 14.23.5.2855

**Comment by assasinwar9** [comment]
if push comes to shove i may take a crack at fixing this myself since this IS opensource, sadly im sick atm with no eta on recovery so.. no eta on me working on fixing this sorry.

**Comment by ThatPolishKid99** [comment]
The only armor that makes you unable to swim is vanilla armor, or not configured modded armor. I don’t think there is a MFR armor set heavy enough to make you not swim.

**Comment by assasinwar9** [comment]
and this feature is active because? look im fine with it only being unconfigured etc but its bound to the weight of the armor in question yes? that same type of check is made for the slowdown and is disabled when said config option is disabled.... sooo it makes perfect sense to have it disable the sinking as well, alot more then having all non configured armor sink you like a rock with no config option to disable that without going through each mod's armor and configuring them etc....

point is it makes less sense to NOT disable the weight factoring for swimming via the slowdown config option, and as iv stated i will try to find a point where i can make the needed changes myself if its not done by then

i hope this isnt coming across as judgmental or demanding, the points iv made are not to make the team (yourself included ofc) working on this seem bad in any way. nor is it to act like this is a 100% must fix or even a priority fix, but it is something im sure alot of modpack makers have ran into and disliked enough to just... not include the mod etc, and i feel thats something to be sad about since minefantasy is amazing, and the team here clearly have put effort into this!
