### ISSUE TITLE
Dragon leads to crash

### ISSUE THREAD

**Issue by J0eGreen** [TeamMFR/MineFantasy-reborn#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Hello, help me please.
I use the mohist server core, the random event of the dragon spawn in the world is not carried out, but when it spawns with the command /sommon minefantasyreforged:dragon
and killing, the server crashes.
Can you please tell me what to do?

### Expected behaviour

it was expected that the random event of summoning a dragon would be executed properly, as in a single player game

### Steps to reproduce

1. Join the server (in my case mohist core)
2. Run command /
3. After executing the command to kill the dragon (in my case, the last hit crashes the server)

### Crashlog

https://gist.github.com/J0eGreen/ae15c9e24ab29671be621a1b3ae20565

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

0.2.0

### Forge version

1.12.2-14.23.5.2860

### Other mods

> randompatches-1.12.2-1.22.1.10.jar
> antiqueatlas-1.12.2-4.6.3.jar
> CraftTweaker2-1.12-4.1.20.682.jar
> jei_1.12.2-4.16.1.302.jar
> AppleSkin-mc1.12-1.0.14.jar
> Baubles-1.12-1.5.2.jar
> BetterMineshaftsForge-1.12.2-2.2.1.jar
> Bloodmoon-MC1.12.2-1.5.3.jar
> Forgelin-1.8.3.jar
> Bountiful-1.12.2-2.2.3.jar
> carryon-1.12.2-1.12.6.20.jar
> Clumps-3.1.2.jar
> CodeChickenLib-1.12.2-3.2.3.358-universal.jar
> collective-1.12.2-3.0.jar
> CraftTweaker2-1.12-4.1.20.682.jar
> CreativeCore_v1.10.70_mc1.12.2.jar
> ctintegration-1.8.0.jar
> doubledoors_1.12.2-2.5.jar
> SereneSeasons-1.12.2-1.2.18-universal.jar
> OreLib-1.12.2-3.6.0.1.jar
> DynamicSurroundings-1.12.2-3.6.1.0.jar
> ExperienceBugFix-1.12.2-1.0.0.0.jar
> FastFurnace-1.12.2-1.3.1.jar
> FastWorkbench-1.12.2-1.7.4.jar
> foamfix-0.10.15-1.12.2.jar
> growthcraft-1.12.2-4.2.2.1.jar
> Harvest-1.12-1.2.8-25.jar
> Hwyla-1.8.26-B41_1.12.2.jar
> InventoryTweaks-1.63.jar
> LootTableTweaker-1.12.2-1.1.14.jar
> pigstep-1.12.jar
> QuickLeafDecay-MC1.12.1-1.2.4.jar
> randomtweaks-1.12.2-2.8.3.1.jar
> RTG-U-1.12.2-6.1.0.0.jar
> SereneTweaks-1.0.jar
> sit-1.12.2-v1.3.jar
> stg-1.12.2-1.2.3.jar
> Thaumcraft-1.12.2-6.1.BETA26.jar
> ThaumcraftResearchPatcher-1.12.2-1.1.3.jar
> ThaumicAugmentation-1.12.2-2.1.9.jar
> Totemic-1.12.2-0.11.7.jar
> VanillaFix-1.0.10-150.jar
> Waystones_1.12.2-4.1.0.jar
> WearableBackpacks-1.12.2-3.1.4.jar
> MineFantasyReforged-1.12.2-0.2.0.jar
>

**Comment by ThatPolishKid99** [comment]
I can't seem to open your crash reports? Can you please upload them in a normal format?

**Comment by J0eGreen** [comment]
> Я не могу открыть ваши отчеты о сбоях? Не могли бы вы загрузить их в нормальном формате?

it should work now

**Comment by ThatPolishKid99** [comment]
Thanks! This will be fixed in the next update

**Comment by J0eGreen** [comment]
Is there any way I can save my world?
connecting to the server causes a crash

**Comment by J0eGreen** [comment]
day 71, the first dragon (young) came and burned me alive

**Comment by ThatPolishKid99** [comment]
Should be fixed in the next update
