### ISSUE TITLE
[Bug] Heated bars not rendering correctly, disappearing when dropped from anvil

### ISSUE THREAD

**Issue by Derpford** [TeamMFR/MineFantasy-reborn#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

In the modpack I'm experimenting with, heated bars of metal (such as the ones that come from hammering a bloom) are invisible.

Furthermore, when removing a stack of heated bars from an anvil's inventory--by clicking on the bars and then clicking outside of the anvil's interface--the bars are removed and a crash occurs.

### Expected behaviour

Heated bars have a visible item sprite.

Heated bars can be removed from the anvil's inventory by dropping them outside of the anvil inventory.

### Steps to reproduce

A) Invisible Bar:
1. Insert Copper Ore and Coal into a bloomery, and light it.
2. Wait for the bloom to be exposed.
3. Hammer the bloom.
4. The item entity's shadow will appear, but the bar itself will be invisible.

B) Bar Crash:
1. Acquire a heated Copper Bar by any means (i.e., from Bloomery, or from a Forge)
2. Insert it into the anvil with tongs.
3. Open the anvil interface.
4. Click on the heated bar, then click outside of the anvil's inventory.
5. The bar will disappear and a crash report will be generated.

### Crashlog

https://gist.github.com/Derpford/ffc1cbc1f6315995f44ab4df9a6c9e6f

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.12.2-0.2.0

### Forge version

1.12.2-14.23.5.2859 (also tested on 2860)

**Comment by Derpford** [comment]
Turning off FoamFix's coremod module resolves invisible heated bars from the bloomery, but doesn't fix the disappearing item glitch.

**Comment by Derpford** [comment]
I tested this with no other mods loaded, and got the following error in my console log:
https://gist.github.com/Derpford/cd4803a50384009995189add5f0d5675

**Comment by Derpford** [comment]
Downgrading to MF:R version 1.12.2-0.1.5 resolves the anvil item removal glitch, but unfortunately the bars don't render unless I remove FoamFix completely on 0.1.5.

**Comment by ThatPolishKid99** [comment]
Should be fixed, at least the crash with Hot Items.
I also recommend turning off the Quark flashing items when they are about to despawn, that is known to cause issues with MFR rendering
