### ISSUE TITLE
[Bug] Dragons Not Drop Hearts

### ISSUE THREAD

**Issue by CCCClear** [TeamMFR/MineFantasy-reborn#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

In the latest version, it seems that dragons no longer drop hearts, which was not the case in the previous version.
I tested all kinds of dragons, but I didn't get a dragon heart.

### Expected behaviour

drop

### Steps to reproduce

kill dragons

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

0.2.0

### Forge version

 1.12.2 - 14.23.5.2860

**Comment by ThatPolishKid99** [comment]
Should be fixed with the latest update
