### ISSUE TITLE
[Bug] [0.2.5]<forged items missing in jei and creative tab>

### ISSUE THREAD

**Issue by H2GamingTW** [TeamMFR/MineFantasy-reborn#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

![image](https://github.com/TeamMFR/MineFantasyReforged/assets/86768934/4b065d36-868a-4554-a10e-72b40b323fa2)

### Expected behaviour

.

### Steps to reproduce

.

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

0.2.5

### Forge version

1.12.2 - 14.23.5.2859

### Other mods

jei and hwyla

**Comment by ThatPolishKid99** [comment]
Should be fixed in the latest hotfix
