### ISSUE TITLE
[Bug] Crafted Items are now Any Items (Includes chest items.

### ISSUE THREAD

**Issue by EmyLightsaber** [TeamMFR/MineFantasy-reborn#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I have a world I previously had made Steel and Black Steel items in, and from the new update all my crafted items are now turned into white "Any Items". 
It would appear all my other items in chests are also "Any Items"

### Expected behaviour

I expected to log back into my server with all my crafted items.

### Steps to reproduce

1. Joined the server
2. Expected to have my previously crafted gear
3. All my crafted items, weapons, and armor are now all white "Any Items".
4. It would appear all my other items in chests are also "Any Items"

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

0.2.0 new

### Forge version

1.12.2 14.23.5.2860

### Other mods

[https://legacy.curseforge.com/minecraft/modpacks/vorps-reborn/files/4608209](https://legacy.curseforge.com/minecraft/modpacks/vorps-reborn/files/4608209)

**Comment by ThatPolishKid99** [comment]
Please provide logs from when you ran it the first time

**Comment by EmyLightsaber** [comment]
[debug.log](https://github.com/TeamMFR/MineFantasyReforged/files/11860198/debug.log)
[latest.log](https://github.com/TeamMFR/MineFantasyReforged/files/11860199/latest.log)

**Comment by EmyLightsaber** [comment]
![2023-06-25_01 29 50](https://github.com/TeamMFR/MineFantasyReforged/assets/85321634/0d910d6f-6cc9-43c4-a07e-7cf033e21277)

**Comment by EmyLightsaber** [comment]
I additionally tried on a new world, and that too had all the crafted tools, weapons, and armor missing along with the recipes.

**Comment by ThatPolishKid99** [comment]
Should be fixed in the latest hotfix
