### ISSUE TITLE
Little Pickaxe

### ISSUE THREAD

**Issue by Hellcat-Brilliant** [TeamMFR/MineFantasy-reborn#6]
Little Pickaxe has a bug that's causing pickups drops 64 per one block

**Comment by ThatPolishKid99** [comment]
We will need more information than this. Preferably proof of the issue occurring and hopefully with steps to replicate the issue.

**Comment by Pelirow** [comment]
Tested a stack each of coal, redstone, diamond, and emerald ore blocks with iron handpick, encrusted handpick, and ignotumite handpick. Currently unable to duplicate this reported bug.

**Comment by Pelirow** [comment]
Videos provided in Discord to show the bug:

https://youtu.be/o82NLEfLPbw
https://youtu.be/eGp9IihxoFA

Can replicate for flux and strong flux; unable to replicate for any vanilla block that drops item upon mining so may be limited to flux and strong flux.

**Comment by Pelirow** [comment]
Update: dupe bug works on all MFR block to item drops, not just flux and strong flux. Still does not appear to work for block to item drops outside of MFR items.

https://youtu.be/sV-c3jo0sDo

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
