### ISSUE TITLE
[Bug] Server Crash

### ISSUE THREAD

**Issue by EmyLightsaber** [TeamMFR/MineFantasy-reborn#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Latest version 028, server crashes with existing world.
[crash-2023-07-23_04.10.57-server.txt](https://github.com/TeamMFR/MineFantasyReforged/files/12137999/crash-2023-07-23_04.10.57-server.txt)

### Expected behaviour

Server should finish booting up.

### Steps to reproduce

1. Start Server
2. Server starts does all the booting up stuff
3. Server is able to be joined.

### Environment (Singleplayer/Server, etc.)

Multiplayer Server

### Mod version

0.2.8

### Forge version

1.12.2 14.23.5.2860

### Other mods

1.1.5 version of Vorps Reborn, list of mods through link: [https://legacy.curseforge.com/minecraft/modpacks/vorps-reborn/files/4654446](url)

**Comment by EmyLightsaber** [comment]
Server also crashes after selecting a new world to generate.
[crash-2023-07-23_04.25.03-server.txt](https://github.com/TeamMFR/MineFantasyReforged/files/12138011/crash-2023-07-23_04.25.03-server.txt)

**Comment by ThatPolishKid99** [comment]
Fixed in latest update. Give it a minute or ten to be approved and then download the new version
