### ISSUE TITLE
[Bug] Long-range weapons can beat mobs by LMB even if the Attack/Destroy button has been changed to another key.

### ISSUE THREAD

**Issue by MamekoCSc** [TeamMFR/MineFantasy-reborn#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While the player is using a long-range weapon(such as spear), she can damage a mob by clicking left mouse button, even if his/her Attack/Destroy button has been changed to another key such as this:
![屏幕截图 2024-05-08 194329](https://github.com/TeamMFR/MineFantasyReforged/assets/169260925/57b1814f-5aa1-41dc-86dd-6e0a530a6f5d)

### Expected behaviour

The player should use Attack/Destroy button to beat a mob.

### Steps to reproduce

1. Change the Attack/Destroy button to right mouse button, and the Use Item/Place Block to left mouse button
2. Pick up a spear or heavy weapon
3. Now you can beat a mob while parrying something
![MFRbug](https://github.com/TeamMFR/MineFantasyReforged/assets/169260925/d3994272-c2e1-49e7-8a63-cfc1e1fa0d2e)

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

0.2.9

### Forge version

1.12.2-14.23.5.2859

### Other mods

!mixinbooter-8.8
CodeChickenLib-1.12.2-3.2.3.358-universal
BiomesOPlenty-1.12.2-7.0.1.2445-universal
comforts-1.12.2-1.4.1.3
Controlling-3.0.12.3
corpse-1.12.2-1.0.8
InventoryTweaks-1.63
MmmMmmMmmMmm-1.12-1.14
Waystones_1.12.2-4.1.0
AppleSkin-mc1.12-1.0.14
DurabilityViewer-1.12-forge14.21.1.2387-1.6
horseinfo-1.0.1
jei_1.12.2-4.16.1.1012
JustEnoughResources-1.12.2-0.9.2.60
moreoverlays-1.15.1-mc1.12.2
NaturesCompass-1.12.2-1.8.5
torohealth-1.12.2-11
XaerosWorldMap_1.38.4_Forge_1.12
Xaeros_Minimap_24.1.1_Forge_1.12
AIImprovements-1.12-0.0.1b3
Born In A Barn 1.8-1.12-1.2
OptiFine_1.12.2_HD_U_G5
spark-forge
ColorUtility-universal-1.0.4
DamageTilt-1.12.2-0.1.0
medivalmusic-1.1

**Comment by ThatPolishKid99** [comment]
Great catch! Will be fixed in the next update

**Comment by ThatPolishKid99** [comment]
Should be fixed in the latest update
