### ISSUE TITLE
[Bug] Right Clicking a Quern Crashes the Client

### ISSUE THREAD

**Issue by EmyLightsaber** [TeamMFR/MineFantasy-reborn#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I tried to open a quern after placing it, and instead the client crashed.

### Expected behaviour

I expected to see the gui open up.

### Steps to reproduce

1. Craft a Quern
2. Place a Quern
3. Right Click said Quern
4. Client Crashes

### Crashlog

https://gist.github.com/EmyLightsaber/d4535b01cb55c115733b483a4ff80032

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.12.2-0.3.0

### Forge version

1.12.2 14.23.5.2860

### Other mods

version 1.9.4 of Vorps Reborn
[https://www.curseforge.com/minecraft/modpacks/vorps-reborn/files/5503260/dependencies](url)

**Comment by ThatPolishKid99** [comment]
should be fixed in the latest release (v0.3.1)
