### ISSUE TITLE
[Bug] Bronze Output not giving correct output

### ISSUE THREAD

**Issue by EmyLightsaber** [TeamMFR/MineFantasy-reborn#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While making bronze, the observed output has it only making 1 bronze for 2 copper and 1 tin.

### Expected behaviour

1. Put 2 copper and 1 tin bars into crucible over lit stone forge.
2. Only 1 bronze is made
3. Bronze Recipe should have made more?

### Steps to reproduce

1. Join a server
2. put 2 copper bars and 1 tin bar into a crucible over a lit stone forge
3. you get 1 bronze.

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

1.12.2-0.3.1

### Forge version

1.12.2 14.23.5.2860

### Other mods

[https://www.curseforge.com/minecraft/modpacks/vorps-reborn/files/5513306/dependencies](url)

**Comment by Lenvill-Jarlsen** [comment]
In a related observation, it appears that MFR's crucible "alloy_ratio_recipe" recipes do not support multiple outputs, even in custom recipes.

**Comment by ThatPolishKid99** [comment]
fixed in latest release
