### ISSUE TITLE
[Bug] Limestone Texture not rendering in JEI

### ISSUE THREAD

**Issue by Lenvill-Jarlsen** [TeamMFR/MineFantasy-reborn#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When looking at recipes in JEI, most recipes (but not all recipes) that use Limestone do not render the limestone block's texture in the JEI menu, displaying the black and purple checkered square instead.
![2024-07-13_16 29 41](https://github.com/user-attachments/assets/cfee874a-7c8a-46ec-b8c6-8eafafb9c943)

### Expected behaviour

That the limestone block would display its normal texture in JEI's menus.

### Steps to reproduce

Include JEI and look up the uses of the limestone block.

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.12.2-0.3.1

### Forge version

1.12.2-14.23.5.2860

### Other mods

None (aside from the dependencies)

**Comment by Lenvill-Jarlsen** [comment]
On closer inspection, it appears that this render bug appears only when the recipe is requesting oredict cobblestone.

**Comment by Lenvill-Jarlsen** [comment]
![2024-07-13_16 39 19](https://github.com/user-attachments/assets/671ac80e-b3d2-4a69-bf18-b5aadb02102a)

**Comment by ThatPolishKid99** [comment]
fixed in latest release
