### ISSUE TITLE
Crash when player punches an ebony trough

### ISSUE THREAD

**Issue by Pelirow** [TeamMFR/MineFantasy-reborn#8]
Reported by user Epic Fail on Discord.

[crash-2021-12-22_15.46.03-client.txt](https://github.com/TeamMFR/MineFantasyReforged/files/7764091/crash-2021-12-22_15.46.03-client.txt)

I am unable to replicate ebony trough crash with empty hand or bucket/trough in hand, no other held items tested. Tested all troughs with no water, partially filled, completely filled via bucket, and filled via right-click then placed.

**Comment by Pelirow** [comment]
UPDATE: Issue is replicable by placing a filled ebony trough, saving and quitting the game, relogging, then the trough will no longer have water. Breaking the previously full but now empty trough by hand will crash.

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
