### ISSUE TITLE
Server crash when server trying to spawn a dragon

### ISSUE THREAD

**Issue by 1170991249** [TeamMFR/MineFantasy-reborn#9]
We haven't met a dragon in Overworld yet, but server crash after player get into Nether for a while, server console shows that server are trying to spawn a dragon but failed, see more in serverlog.txt
[crash-2021-12-23_10.18.18-server.txt](https://github.com/TeamMFR/MineFantasyReforged/files/7766278/crash-2021-12-23_10.18.18-server.txt)
[serverlog.txt](https://github.com/TeamMFR/MineFantasyReforged/files/7766283/serverlog.txt)

**Comment by ThatPolishKid99** [comment]
closed this in 5fb41e0
